# A composite action to extract environment variables from a file

name: Extract data string from file
description: Extract data string from a file
inputs:
  path:
    description: Path to the file containing the data
    required: true
outputs:
  data:
    description: Data string extracted from the file
    value: ${{ steps.extract-data-string.outputs.data }}
  error:
    description: Error message if any
    value: ${{ steps.extract-data-string.outputs.error }}
runs:
  using: 'composite'

  steps:
    - name: Validate and extract contents of ${{ inputs.path }} to $GITHUB_OUTPUT
      id: extract-data-string
      shell: bash
      run: |
        if [ -z "${{ inputs.path }}" ]; then
          ERROR_MESSAGE="Path is required"
          echo "::error::$ERROR_MESSAGE"
          echo "error=$ERROR_MESSAGE" >> $GITHUB_OUTPUT
        elif [ ! -e "${{ inputs.path }}" ]; then
          ERROR_MESSAGE="Path does not exist"
          echo "::error::$ERROR_MESSAGE"
          echo "error=$ERROR_MESSAGE" >> $GITHUB_OUTPUT
        elif [ -d "${{ inputs.path }}" ]; then
          ERROR_MESSAGE="Path is a directory"
          echo "::error::$ERROR_MESSAGE"
          echo "error=$ERROR_MESSAGE" >> $GITHUB_OUTPUT
        else
          DATA=$(cat "${{ inputs.path }}")
          {
            echo "data<<EOF"
            echo "$DATA"
            echo "EOF"
          } >> $GITHUB_OUTPUT
        fi
