# A composite action to extract environment variables from a file

name: Extract data string from file
description: Extract data string from a file
inputs:
  path:
    description: Path to the file containing the data
    required: true
outputs:
  data:
    description: Data string extracted from the file
    value: ${{ steps.extract-data-string.outputs.data }}
  error:
    description: Error message if any
    value: ${{ steps.extract-data-string.outputs.error }}
  success:
    description: Whether the operation was successful
    value: ${{ steps.extract-data-string.outputs.success }}
runs:
  using: 'composite'

  steps:
    - name: Validate and extract contents of ${{ inputs.path }} to $GITHUB_OUTPUT
      id: extract-data-string
      shell: bash
      env:
        TESTING_MODE: ${{ env.TESTING_MODE || 'false' }}
      run: |
        bash ./.github/actions/extract-data-string-from-file/extract-data-string-from-file.sh ${{ inputs.path }}
