# A composite action to extract environment variables from a file

name: Extract data string from file
description: Extract data string from a file
inputs:
  path:
    description: Path to the file containing the data
    required: true
outputs:
  data:
    description: Data string extracted from the file
    value: ${{ steps.extract-data-string.outputs.data }}
runs:
  using: 'composite'

  steps:
    - name: Validate and extract contents of ${{ inputs.path }} to $GITHUB_OUTPUT
      id: extract-data-string
      shell: bash
      run: |
        if [ -z "${{ inputs.path }}" ]; then
          echo "::error::Path is required" && exit 1
        elif [ ! -e "${{ inputs.path }}" ]; then
          echo "::error::Path does not exist" && exit 1
        elif [ -d "${{ inputs.path }}" ]; then
          echo "::error::Path is a directory" && exit 1
        else
          DATA=$(cat "${{ inputs.path }}")
          {
            echo "data<<EOF"
            echo "$DATA"
            echo "EOF"
          } >> $GITHUB_OUTPUT
        fi
