# Workflow to build libs-base

name: BUILD-LIBS-BASE
on: [workflow_dispatch, workflow_call]

jobs:
  build-libs-base:
    name: Build libs-base latest
    runs-on: windows-latest
    needs: [build-tools-make]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu

      - name: "Retrieve tools-make cache"
        uses: actions/cache/restore@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: "Install tools-make"
        run: |
          cd tools-make
          make -j $(nproc) install

      - name: "Checkout libs-base"
        uses: actions/checkout@v4
        with:
          repository: gnustep/libs-base
#          ref: base-1_29_0
# Using latest
# Needs https://github.com/gnustep/libs-base/pull/295
          path: libs-base

      - name: "Configure and build libs-base"
        run: |
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          cd libs-base
          ./configure
          make -j $(nproc)

      - name: "Cache libs-base build"
        uses: actions/cache/save@v3
        with:
          path: libs-base
          key: cache-libs-base-${{ github.run_id }}-${{ github.run_attempt }}


########################################

  build-tools-make:
    uses: ./.github/workflows/build-tools-make.yml
