# Workflow to compile Oolite and necessary dependencies

name: BUILD-OOLITE
on: workflow_dispatch

########################################

jobs:
  build-oolite:
    runs-on: windows-latest
    needs: [build-tools-make, build-libs-base, build-sdl]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel git mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu

      - name: "Download tools-make build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: tools-make
          path: tools-make

      - name: "Install tools-make"
        run: |
          cd tools-make
          make install

      - name: "Download libs-base build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: libs-base
          path: libs-base

      - name: "Install libs-base"
        run: |
          cd libs-base
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          make install

      - name: "Download SDL build artifacts"
        uses: actions/download-artifact@v3
        with:
          name: sdl-build
          path: SDL-1.2.13

      - name: "Install SDL"
        run: |
          cd SDL-1.2.13
          make install

      - name: "Checkout oolite"
        uses: actions/checkout@v4
        with:
          repository: OOliteProject/oolite
          path: oolite
          submodules: recursive

      - name: "Configure and build Oolite"
        run: |
          cd oolite
          sed -i '36 s/$/ -fobjc-exceptions -fcommon/' GNUMakefile
          sed -i '25 s/^#//' GNUMakefile
          sed -i '33 s/-l$(JS_IMPORT_LIBRARY) /-L$(JS_LIB_DIR) &/' GNUMakefile
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          make -f Makefile release

########################################

  build-tools-make:
    uses: ./.github/workflows/build-tools-make.yml

########################################

  build-libs-base:
    uses: ./.github/workflows/build-libs-base.yml

########################################

  build-sdl:
    uses: ./.github/workflows/build-sdl.yml
