# Workflow to build SDL

name: BUILD-SDL
on: [workflow_dispatch, workflow_call]

jobs:
  build-sdl:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel autoconf mingw-w64-x86_64-gcc

      - name: "Download oolite-win-deps for patch"
        uses: actions/checkout@v4
        with:
          repository: OoliteProject/oolite-windows-dependencies
          path: Windows-deps

      - name: "Download and extract SDL"
        run: |
          wget https://sourceforge.net/projects/libsdl/files/SDL/1.2.13/SDL-1.2.13.tar.gz
          tar -xf SDL-1.2.13.tar.gz

      - name: "Apply Oolte patch to SDL"
        run: |
          patch -s -d SDL-1.2.13 -p1 < Windows-deps/OOSDLWin32Patch/OOSDLdll_x64.patch

      - name: "Configure and build SDL"
        run: |
          cd SDL-1.2.13
          ./autogen.sh
          ./configure
          sed -i '/^EXTRA_LDFLAGS/ s/$/ -ldxerr8 -ldinput8 -lole32/' Makefile
          make

      - name: "Upload SDL build artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: sdl-build
          path: SDL-1.2.13/*
          if-no-files-found: error
