# Workflow to compile Oolite and necessary dependencies

name: BUILD-OOLITE
on: workflow_dispatch

########################################

jobs:
  build-oolite:
    name: Build Oolite
    runs-on: windows-latest
    needs: [build-tools-make, build-libs-base, build-sdl]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel git mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu

      - name: "Retrieve tools-make cache"
        uses: actions/cache@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: "Install tools-make"
        run: |
          cd tools-make
          make -j $(nproc) install

      - name: "Retrieve libs-base cache"
        uses: actions/cache@v3
        with:
          path: libs-base
          key: cache-libs-base-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: "Install libs-base"
        run: |
          cd libs-base
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          make -j $(nproc) install

      - name: "Retrieve SDL cache"
        uses: actions/cache@v3
        with:
          path: SDL-1.2.13
          key: cache-sdl-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: "Install SDL"
        run: |
          cd SDL-1.2.13
          make -j $(nproc) install

      - name: "Checkout oolite"
        uses: actions/checkout@v4
        with:
          repository: OOliteProject/oolite
          path: oolite
          submodules: recursive

      - name: "Configure and build Oolite"
        run: |
          cd oolite
          sed -i '36 s/$/ -fobjc-exceptions -fcommon/' GNUMakefile
          sed -i '25 s/^#//' GNUMakefile
          sed -i '33 s/-l$(JS_IMPORT_LIBRARY) /-L$(JS_LIB_DIR) &/' GNUMakefile
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          make -j $(nproc) -f Makefile release

########################################

  build-tools-make:
    uses: ./.github/workflows/build-tools-make.yml

########################################

  build-libs-base:
    uses: ./.github/workflows/build-libs-base.yml

########################################

  build-sdl:
    uses: ./.github/workflows/build-sdl.yml
