# Workflow to build tools-make

name: BUILD-TOOLS-MAKE
on: [workflow_dispatch, workflow_call]

jobs:
  build-tools-make:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel mingw-w64-x86_64-gcc-objc

      - name: "Checkout tools-make"
        uses: actions/checkout@v4
        with:
          repository: gnustep/tools-make
          ref: make-2_4_0
          path: tools-make

      - name: "Configure and build tools-make"
        run: |
          cd tools-make
          ./configure
          make

      - name: "Cache tools-make build"
        uses: actions/cache@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ github.run_id }}-${{ github.run_attempt }}
