  name: Clear Oolite Caches

  on:
    push:
      branches:
        - main

  jobs:
    clear-oolite-caches:
      name: Clear Oolite Caches
      runs-on: windows-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - name: Checkout this repository
          uses: actions/checkout@v4

        - name: List Oolite caches
          run: |
            gh cache list | grep cache-oolite | awk '{print $2}' > cache-list.txt
            cat cache-list.txt

        - name: Delete Oolite caches
          run: |
            foreach ($cache in Get-Content cache-list.txt) {
              echo $cache
              gh cache delete $cache
            }

        - name: List caches
          run: |
            gh cache list
