# Workflow to compile Oolite and necessary dependencies

name: MSYS2-MINGW64-ACTIONS-SPLIT
on: 
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run build tests"
        required: false
        type: boolean
        default: false
env:
  TOOLS_MAKE_VERSION: make-2_9_1
  LIBS_MAKE_VERSION: 1942313dea27ceafa3bb107c427be813094c04e3
  SDL_VERSION: https://sourceforge.net/projects/libsdl/files/SDL/1.2.13/SDL-1.2.13.tar.gz
jobs:

########################################
########################################
########################################

# Build Oolite and it's installers

  build-oolite:
    name: Build Oolite
    runs-on: windows-latest
    needs: [build-tools-make, build-libs-base, build-sdl]
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        build_type: [release, release-deployment, release-snapshot, debug]
      fail-fast: false
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel git mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu mingw-w64-x86_64-libxslt

      - name: "Retrieve tools-make cache"
        uses: actions/cache/restore@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ env.TOOLS_MAKE_VERSION }}-${{ hashFiles('**/tools-make-build.sh') }}
          fail-on-cache-miss: true

      - name: "Install tools-make"
        run: |
          cd tools-make
          make -j $(nproc) install

      - name: "Retrieve libs-base cache"
        uses: actions/cache/restore@v3
        with:
          path: libs-base
          key: cache-libs-base-${{ env.LIBS_MAKE_VERSION }}-${{ hashFiles('**/libs-base-build.sh') }}
          fail-on-cache-miss: true

      - name: "Install libs-base"
        run: |
          cd libs-base
          . /mingw64/share/GNUstep/Makefiles/GNUstep.sh
          make -j $(nproc) install

      - name: "Retrieve SDL cache"
        uses: actions/cache/restore@v3
        with:
          path: SDL-1.2.13
          key: cache-sdl-${{ env.SDL_VERSION }}-${{ hashFiles('**/sdl-build.sh') }}
          fail-on-cache-miss: true

      - name: "Install SDL"
        run: |
          cd SDL-1.2.13
          make -j $(nproc) install

      - name: "Checkout oolite"
        uses: actions/checkout@v4
        with:
          repository: OoliteProject/oolite
          path: oolite
          submodules: recursive

      - name: "Configure and build Oolite"
        run: |
          cd oolite
          sed -i '36 s/$/ -fobjc-exceptions -fcommon/' GNUMakefile
          sed -i '25 s/^#//' GNUMakefile
          sed -i '33 s/-l$(JS_IMPORT_LIBRARY) /-L$(JS_LIB_DIR) &/' GNUMakefile
          sed -i '452 s/objc.make/tool.make/' GNUMakefile
          sed -i 's/OBJC_PROGRAM_NAME/TOOL_NAME/' GNUMakefile
          sed -i 's/OBJC_PROGRAM_NAME/TOOL_NAME/' GNUmakefile.postamble 
          sed -i 's/pkg-win/pkg-win-release/' Makefile
          . /mingw64/share/GNUstep/Makefiles/GNUstep.sh
          make -j $(nproc) -f Makefile ${{ matrix.build_type }}

      - name: "Cache Oolite build"
        uses: actions/cache/save@v3
        with:
          path: oolite
          key: cache-oolite-${{ matrix.build_type }}-${{ github.run_id }}-${{ github.run_attempt }}


########################################

# Build the installers.

  build-oolite-installers:
    name: Build Oolite installers
    runs-on: windows-latest
    needs: [build-tools-make, build-oolite]
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        build_type: [release, release-deployment, release-snapshot, debug]
      fail-fast: false
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel git mingw-w64-x86_64-nsis

      - name: "Retrieve tools-make cache"
        uses: actions/cache/restore@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ env.TOOLS_MAKE_VERSION }}-${{ hashFiles('**/tools-make-build.sh') }}
          fail-on-cache-miss: true
    
      - name: "Install tools-make"
        run: |
          cd tools-make
          make -j $(nproc) install
          
      - name: "Retrieve Oolite cache"
        uses: actions/cache/restore@v3
        with:
          path: oolite
          key: cache-oolite-${{ matrix.build_type }}-${{ github.run_id }}-${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: "Build installers"
        run: |
          cd oolite
          . /mingw64/share/GNUstep/Makefiles/GNUstep.sh
          make -j $(nproc) -f Makefile pkg-win-${{ matrix.build_type }}


########################################
########################################
########################################

# Build the dependencies that need to be installed to build Oolite.

  build-tools-make:
    name: Build tools-make
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Check for pre-existing tools-make cache"
        id: check-cache
        uses: actions/cache/restore@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ env.TOOLS_MAKE_VERSION }}-${{ hashFiles('**/tools-make-build.sh') }}
          lookup-only: true

      - name: "Early exit if cache exists"
        id: early-exit
        if: steps.check-cache.outputs.cache-hit == 'true' 
        shell: bash
        run: |
          echo "tools-make cache exists, exiting early"

      - name: "Set up msys2"
        if: steps.early-exit.conclusion != 'success'  
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel mingw-w64-x86_64-gcc-objc

      - name: "Checkout tools-make"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/checkout@v4
        with:
          repository: gnustep/tools-make
          path: tools-make
          ref: ${{ env.TOOLS_MAKE_VERSION }}

      - name: "Configure and build tools-make"
        if: steps.early-exit.conclusion != 'success'  
        run: |
          bash ./tools-make-build.sh

      - name: "Cache tools-make build"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/cache/save@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ env.TOOLS_MAKE_VERSION }}-${{ hashFiles('**/tools-make-build.sh') }}
  
########################################

  build-libs-base:
    name: Build libs-base
    runs-on: windows-latest
    needs: [build-tools-make]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Check for pre-existing libs-base cache"
        id: check-cache
        uses: actions/cache/restore@v3
        with:
          path: libs-base
          key: cache-libs-base-${{ env.LIBS_MAKE_VERSION }}-${{ hashFiles('**/libs-base-build.sh') }}
          lookup-only: true

      - name: "Early exit if cache exists"
        id: early-exit
        if: steps.check-cache.outputs.cache-hit == 'true' 
        shell: bash
        run: |
          echo "libs-base cache exists, exiting early"

      - name: "Set up msys2"
        if: steps.early-exit.conclusion != 'success'  
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu mingw-w64-x86_64-libxslt

      - name: "Retrieve tools-make cache"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/cache/restore@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ env.TOOLS_MAKE_VERSION }}-${{ hashFiles('**/tools-make-build.sh') }}
          fail-on-cache-miss: true
    
      - name: "Install tools-make"
        if: steps.early-exit.conclusion != 'success'  
        run: |
          cd tools-make
          make -j $(nproc) install

      - name: "Checkout libs-base"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/checkout@v4
        with:
          repository: gnustep/libs-base
          path: libs-base
          ref: ${{ env.LIBS_MAKE_VERSION }}

      - name: "Configure and build libs-base"
        if: steps.early-exit.conclusion != 'success'  
        run: |
          bash ./libs-base-build.sh

      - name: "Cache libs-base build"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/cache/save@v3
        with:
          path: libs-base
          key: cache-libs-base-${{ env.LIBS_MAKE_VERSION }}-${{ hashFiles('**/libs-base-build.sh') }}
  
########################################

  build-sdl:
    name: Build SDL
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Check for pre-existing SDL cache"
        id: check-cache
        uses: actions/cache/restore@v3
        with:
          path: SDL-1.2.13
          key: cache-sdl-${{ env.SDL_VERSION }}-${{ hashFiles('**/sdl-build.sh') }}
          lookup-only: true

      - name: "Early exit if cache exists"
        id: early-exit
        if: steps.check-cache.outputs.cache-hit == 'true' 
        shell: bash
        run: |
          echo "SDL cache exists, exiting early"

      - name: "Set up msys2"
        if: steps.early-exit.conclusion != 'success'  
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel autoconf mingw-w64-x86_64-gcc

      - name: "Download oolite-win-deps SDL patch"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/checkout@v4
        with:
          repository: OoliteProject/oolite-windows-dependencies
          path: Windows-deps

      - name: "Download and extract SDL"
        if: steps.early-exit.conclusion != 'success'  
        run: |
          wget ${{ env.SDL_VERSION }}
          tar -xf SDL-1.2.13.tar.gz

      - name: "Configure and build SDL"
        if: steps.early-exit.conclusion != 'success'  
        run: |
          bash ./sdl-build.sh

      - name: "Cache SDL build"
        if: steps.early-exit.conclusion != 'success'  
        uses: actions/cache/save@v3
        with:
          path: SDL-1.2.13
          key: cache-sdl-${{ env.SDL_VERSION }}-${{ hashFiles('**/sdl-build.sh') }}

########################################
########################################
########################################

# Test the dependencies.
# These jobs only run if the build jobs have been successful and the run_tests input is true.

  test-libs-base:
    name: Test libs-base
    runs-on: windows-latest
    if: ${{ inputs.run_tests }}
    needs: [build-tools-make, build-libs-base]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu mingw-w64-x86_64-libxslt

      - name: "Retrieve tools-make cache"
        uses: actions/cache/restore@v3
        with:
          path: tools-make
          key: cache-tools-make-${{ env.TOOLS_MAKE_VERSION }}-${{ hashFiles('**/tools-make-build.sh') }}
          fail-on-cache-miss: true

      - name: "Install tools-make"
        run: |
          cd tools-make
          make -j $(nproc) install

      - name: "Retrieve libs-base cache"
        uses: actions/cache/restore@v3
        with:
          path: libs-base
          key: cache-libs-base-${{ env.LIBS_MAKE_VERSION }}-${{ hashFiles('**/libs-base-build.sh') }}
          fail-on-cache-miss: true

      - name: "Install libs-base"
        run: |
          cd libs-base
          . /mingw64/share/GNUstep/Makefiles/GNUstep.sh
          make -j $(nproc) install

      - name: "Test libs-base"
        run: |
          . /mingw64/share/GNUstep/Makefiles/GNUstep.sh
          cd libs-base
          make -j $(nproc) check

      - name: Upload tests.log
        uses: actions/upload-artifact@v3
        with:
          name: libs-base_test.log
          path: |
            libs-base/Tests/tests.log

########################################

  test-sdl:
    name: Test SDL
    runs-on: windows-latest
    if: ${{ inputs.run_tests }}
    needs: [build-sdl]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v3

      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            base-devel autoconf mingw-w64-x86_64-gcc

      - name: "Retrieve SDL cache"
        uses: actions/cache/restore@v3
        with:
          path: SDL-1.2.13
          key: cache-sdl-${{ env.SDL_VERSION }}-${{ hashFiles('**/sdl-build.sh') }}
          fail-on-cache-miss: true

      - name: "Install SDL"
        run: |
          cd SDL-1.2.13
          make -j $(nproc) install

      - name: "Build SDL tests"
        run: |
          cd SDL-1.2.13/test
          ./configure
          make -j $(nproc)

 ########################################
