name: MSYS2-MINGW64
on: workflow_dispatch

jobs:
  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          bash ./oolite-from-fresh-msys2-mingw64.sh
