name: MSYS2-MINGW64-ACTIONS
on: workflow_dispatch

jobs:
  msys2-mingw64:
    name: Build Oolite
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Set up msys2"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
# Install Build tools
# Install libs-base dependencies
# Install build dep for SDL
          install: |
            base-devel git mingw-w64-x86_64-gcc-objc
            mingw-w64-x86_64-libffi mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls mingw-w64-x86_64-icu
            autoconf

      - name: "Checkout tools-make"
        uses: actions/checkout@v4
        with:
          repository: gnustep/tools-make
          ref: make-2_4_0
          path: tools-make

      - name: "Configure, build and install tools-make"
        run: |
          cd tools-make
          ./configure
          make -j $(nproc)
          make -j $(nproc) install

      - name: "Checkout libs-base"
        uses: actions/checkout@v4
        with:
          repository: gnustep/libs-base
          ref: base-1_29_0
          path: libs-base

      - name: "Configure, build and install libs-base"
        run: |
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          cd libs-base
          ./configure
          make -j $(nproc)
          make -j $(nproc) install

      - name: "Checkout oolite"
        uses: actions/checkout@v4
        with:
          repository: OoliteProject/oolite
          path: oolite
          submodules: recursive

      - name: "Download and extract SDL"
        run: |
          wget https://sourceforge.net/projects/libsdl/files/SDL/1.2.13/SDL-1.2.13.tar.gz
          tar -xf SDL-1.2.13.tar.gz

      - name: "Apply Oolte patch to SDL"
        run: |
          patch -s -d SDL-1.2.13 -p1 < oolite/deps/Windows-deps/OOSDLWin32Patch/OOSDLdll_x64.patch

      - name: "Configure, build and install SDL"
        run: |
          cd SDL-1.2.13
          ./autogen.sh
          ./configure
          sed -i '/^EXTRA_LDFLAGS/ s/$/ -ldxerr8 -ldinput8 -lole32/' Makefile
          make -j $(nproc)
          make -j $(nproc) install

      - name: "Configure and build Oolite"
        run: |
          cd oolite
          sed -i '36 s/$/ -fobjc-exceptions -fcommon/' GNUMakefile
          sed -i '25 s/^#//' GNUMakefile
          sed -i '33 s/-l$(JS_IMPORT_LIBRARY) /-L$(JS_LIB_DIR) &/' GNUMakefile
          . /mingw64/System/Library/Makefiles/GNUstep.sh
          make -j $(nproc) -f Makefile release
